// gen-reference writes docs/api.md, docs/cli.md and docs/mcp.md from the
// binary that serves them.
//
// The same document `GET /api/v1/reference` returns and the console renders, in
// Markdown, so the repository's documentation of its own API cannot describe a
// version of Pando that no longer exists. `make reference` writes them and
// `make check` fails on a diff — the same shape as the generated API types and
// the requirements index, and for the same reason: a file that has to be
// updated by remembering is a file that is wrong.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/bemeek-io/pando/internal/httpapi"
	"github.com/bemeek-io/pando/internal/reference"
)

const preamble = "<!-- Generated by cmd/gen-reference from the running code. Do not edit by hand;\n" +
	"     run `make reference`. `make check` fails when this file is out of date. -->\n\n"

func main() {
	dir := "docs"
	if len(os.Args) > 1 {
		dir = os.Args[1]
	}

	doc := httpapi.Reference()

	for name, body := range map[string]string{
		"api.md": api(doc),
		"cli.md": cliDoc(doc),
		"mcp.md": mcpDoc(doc),
	} {
		path := filepath.Join(dir, name)
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil { //nolint:gosec // G306: documentation, world-readable on purpose.
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		fmt.Println("wrote", path)
	}
}

func api(doc reference.Document) string {
	var b strings.Builder
	b.WriteString(preamble)
	b.WriteString("# The Pando API\n\n")
	b.WriteString("Everything Pando does, it does through this API. The console, the CLI and the MCP\n")
	b.WriteString("server are clients of it and none of them has a capability it lacks (R-261).\n\n")
	b.WriteString("Base path: `" + doc.API.BasePath + "`. Times are RFC 3339 in UTC. IDs are prefixed and\n")
	b.WriteString("opaque — `app_01HQ8…`, `spec_…`, `tok_…`.\n\n")

	b.WriteString("## Authenticating\n\n")
	for _, auth := range doc.API.Auth {
		b.WriteString("**" + auth.Name + "** — `" + auth.How + "`\n\n")
		b.WriteString(auth.Description + "\n\n")
	}

	b.WriteString("## Endpoints\n\n")
	b.WriteString("The verb column is the authorization verb the endpoint asks for. Blank means it\n")
	b.WriteString("asks for nothing beyond being signed in. There is no implication graph: holding\n")
	b.WriteString("one verb says nothing about another (R-082).\n\n")

	for _, group := range groups(doc.API.Routes) {
		b.WriteString("### " + group + "\n\n")
		b.WriteString("| Endpoint | Verb | What it does |\n| --- | --- | --- |\n")
		for _, route := range doc.API.Routes {
			if route.Group != group {
				continue
			}
			verb := route.Verb
			if verb != "" {
				verb = "`" + verb + "`"
			}
			fmt.Fprintf(&b, "| `%s %s` | %s | %s |\n", route.Method, route.Path, verb, route.Summary)
		}
		b.WriteString("\n")
	}

	b.WriteString("## Errors\n\n")
	b.WriteString("Every error crossing this boundary carries the same envelope: a stable machine\n")
	b.WriteString("`code`, a human `message`, an optional `remedy`, `details` and the `request_id`\n")
	b.WriteString("that finds the log line. Branch on the code; the message may be reworded.\n\n")
	b.WriteString("| Code | HTTP | Meaning |\n| --- | --- | --- |\n")
	for _, e := range doc.Errors {
		fmt.Fprintf(&b, "| `%s` | %d | %s |\n", e.Code, e.Status, e.Meaning)
	}
	b.WriteString("\n")
	return b.String()
}

func cliDoc(doc reference.Document) string {
	var b strings.Builder
	b.WriteString(preamble)
	b.WriteString("# The Pando CLI\n\n")
	b.WriteString("Every command here is a wrapper over an endpoint in [the API](api.md). It reads\n")
	b.WriteString("repetitively on purpose: a command that did something the API cannot do would be\n")
	b.WriteString("a capability the console and MCP could never have (R-261).\n\n")
	b.WriteString("## Installing\n\n")
	b.WriteString("The CLI is the same binary as the server (R-253), pointed at an installation over\n")
	b.WriteString("its API. It goes on your own machine rather than on the host, and everything it\n")
	b.WriteString("does can also be done in the console.\n\n")
	b.WriteString("**macOS, and Linux with Homebrew:**\n\n")
	b.WriteString("```\nbrew install " + doc.Install.Homebrew + "\n```\n\n")
	b.WriteString("**Debian, Ubuntu, Fedora, Alpine:** every release attaches " +
		list(doc.Install.Packages, "`.%s`") + " packages, named\n")
	b.WriteString("`" + doc.Install.Package + "`. Take a version from the\n")
	b.WriteString("[releases page](" + doc.Install.Repo + "/releases) and download it:\n\n")
	b.WriteString("```\n" + packageRecipe(doc.Install, "deb", "amd64") + "\n```\n\n")
	b.WriteString("For `.rpm`, `dnf install` the same file; for `.apk`,\n")
	b.WriteString("`apk add --allow-untrusted`. On an ARM machine, `arm64` in place of `amd64`.\n\n")

	b.WriteString("**Anything else:** plain tarballs, named `" + doc.Install.Archive + "`, for " +
		list(doc.Install.Platforms, "`%s`") + ":\n\n")
	b.WriteString("```\n" + archiveRecipe(doc.Install, "darwin", "arm64") + "\n```\n\n")
	b.WriteString("Every release is published with a checksum file signed by the release workflow;\n")
	b.WriteString("verifying it is described in [releasing.md](releasing.md).\n\n")
	b.WriteString("**From source**, with a Go toolchain:\n\n")
	b.WriteString("```\ngo install " + doc.Install.Module + "@latest\n```\n\n")
	b.WriteString("**Or install nothing.** A Compose installation already has the binary in it:\n\n")
	b.WriteString("```\n" + doc.Install.InContainer + " app list\n```\n\n")

	b.WriteString("## Connecting\n\n")
	b.WriteString("```\n" + strings.Replace(doc.Connect.LoginCmd, "<server-url>", "https://pando.example.com", 1) + "\n```\n\n")
	b.WriteString("`pando login` stores a delegated token under your home directory, which is right\n")
	b.WriteString("for a person at a terminal and no use to CI or a container. Those get the same\n")
	b.WriteString("thing from the environment — mint a token in the console under **API and tools**,\n")
	b.WriteString("or with `pando token create`:\n\n")
	b.WriteString("```\nexport " + doc.Connect.ServerEnv + "=https://pando.example.com\nexport " +
		doc.Connect.TokenEnv + "=tok_…\n```\n\n")
	b.WriteString("The environment beats the stored file; `--server` beats both.\n\n")
	b.WriteString("## Commands\n\n")
	for _, c := range doc.CLI {
		writeCommand(&b, c, 3)
	}
	return b.String()
}

func writeCommand(b *strings.Builder, c reference.Command, depth int) {
	b.WriteString(strings.Repeat("#", depth) + " `" + c.Name + "`\n\n")
	if c.Summary != "" {
		b.WriteString(c.Summary + "\n\n")
	}
	b.WriteString("```\n" + c.Use + "\n```\n\n")
	if c.Details != "" && c.Details != c.Summary {
		b.WriteString(c.Details + "\n\n")
	}
	if len(c.Flags) > 0 {
		b.WriteString("| Flag | Default | What it does |\n| --- | --- | --- |\n")
		for _, f := range c.Flags {
			name := "`--" + f.Name + "`"
			if f.Shorthand != "" {
				name = "`-" + f.Shorthand + "`, " + name
			}
			def := ""
			if f.Default != "" && f.Default != "false" {
				def = "`" + f.Default + "`"
			}
			fmt.Fprintf(b, "| %s | %s | %s |\n", name, def, f.Description)
		}
		b.WriteString("\n")
	}
	for _, child := range c.Children {
		writeCommand(b, child, depth+1)
	}
}

func mcpDoc(doc reference.Document) string {
	var b strings.Builder
	b.WriteString(preamble)
	b.WriteString("# Pando over MCP\n\n")
	b.WriteString("An agent holds a token and is therefore a principal like any other: it acts as\n")
	b.WriteString("its owner, is bounded by their live grants, and its actions land in the audit log\n")
	b.WriteString("under their name (R-262).\n\n")
	b.WriteString("## Connecting\n\n")
	b.WriteString("`" + doc.Connect.MCPCmd + "` speaks MCP over stdio. In Claude Code:\n\n")
	b.WriteString("```\nclaude mcp add pando -- " + doc.Connect.MCPCmd + "\n```\n\n")
	b.WriteString("Or, by hand, in an MCP client's configuration:\n\n")
	b.WriteString("```json\n{\n  \"mcpServers\": {\n    \"pando\": {\n      \"command\": \"pando\",\n" +
		"      \"args\": [\"mcp\"],\n      \"env\": {\n        \"" + doc.Connect.ServerEnv +
		"\": \"https://pando.example.com\",\n" +
		"        \"" + doc.Connect.TokenEnv + "\": \"tok_…\"\n      }\n    }\n  }\n}\n```\n\n")
	b.WriteString("## Tools\n\n")
	b.WriteString("One tool per endpoint, deliberately. A tool that composed several calls would be\n")
	b.WriteString("a capability the CLI and console do not have. Exec, reading a secret's value,\n")
	b.WriteString("changing grants or policy, and deleting a user are not offered: host policy is the\n")
	b.WriteString("boundary (O-12), and offering a tool policy will refuse wastes the agent's turn.\n\n")
	b.WriteString("| Tool | What it does | Arguments |\n| --- | --- | --- |\n")
	for _, tool := range doc.MCP {
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", tool.Name, tool.Description, arguments(tool.Schema))
	}
	b.WriteString("\n")
	return b.String()
}

// arguments renders a tool's JSON schema as the list of argument names, marking
// the required ones.
func arguments(schema map[string]any) string {
	props, _ := schema["properties"].(map[string]any)
	if len(props) == 0 {
		return "none"
	}

	required := map[string]bool{}
	if list, ok := schema["required"].([]string); ok {
		for _, name := range list {
			required[name] = true
		}
	}

	names := make([]string, 0, len(props))
	for name := range props {
		names = append(names, name)
	}
	sort.Strings(names)

	out := make([]string, 0, len(names))
	for _, name := range names {
		if required[name] {
			out = append(out, "`"+name+"`")
			continue
		}
		out = append(out, "`"+name+"` (optional)")
	}
	return strings.Join(out, ", ")
}

// packageRecipe is the download-and-install lines for one package format.
//
// Written out for a real format and architecture rather than left as
// placeholders: an instruction with three angle brackets in it is an
// instruction somebody has to assemble before they can run it, and assembling
// it is where they get it wrong.
func packageRecipe(in reference.Install, format, arch string) string {
	file := strings.NewReplacer("<format>", format, "<arch>", arch).Replace(in.Package)
	url := in.Download + file
	return strings.Join([]string{
		"VERSION=" + exampleVersion + "   # the release you want",
		"curl -LO " + strings.ReplaceAll(url, "<version>", "${VERSION}"),
		"sudo apt install ./" + strings.ReplaceAll(file, "<version>", "${VERSION}"),
	}, "\n")
}

// archiveRecipe is the same for a tarball.
func archiveRecipe(in reference.Install, os, arch string) string {
	file := strings.NewReplacer("<os>", os, "<arch>", arch).Replace(in.Archive)
	url := in.Download + file
	return strings.Join([]string{
		"VERSION=" + exampleVersion + "   # the release you want",
		"curl -LO " + strings.ReplaceAll(url, "<version>", "${VERSION}"),
		"tar xzf " + strings.ReplaceAll(file, "<version>", "${VERSION}"),
		"sudo mv pando /usr/local/bin/",
	}, "\n")
}

// exampleVersion stands in for whatever is current. It is a placeholder in a
// shell variable rather than a version number in every line, so a reader
// changes one thing and the rest of the block is correct.
const exampleVersion = "0.2.0"

// list renders a slice as prose: "`a`, `b` and `c`".
func list(items []string, format string) string {
	quoted := make([]string, 0, len(items))
	for _, item := range items {
		quoted = append(quoted, fmt.Sprintf(format, item))
	}
	switch len(quoted) {
	case 0:
		return ""
	case 1:
		return quoted[0]
	default:
		return strings.Join(quoted[:len(quoted)-1], ", ") + " and " + quoted[len(quoted)-1]
	}
}

func groups(routes []reference.Route) []string {
	seen := map[string]bool{}
	var out []string
	for _, r := range routes {
		if !seen[r.Group] {
			seen[r.Group] = true
			out = append(out, r.Group)
		}
	}
	return out
}
