// Generated by cmd/gen-api-types. Do not edit.
//
// These are the Go types the API serializes, mechanically translated. R-261
// makes the API authoritative, and design 08 §1.2 says these are generated for
// that reason: a hand-written type is a second opinion about what the server
// returns, and the two drift the first time a field is added.
//
// Regenerate with: npm run types

export interface App {
  id: string;
  name: string;
  slug: string;
  owner_user_id: string;
  state: string;
  desired_state: string;
  pinned_spec_id?: string;
  source: Source;
  created_at: string;
  updated_at: string;
  deleted_at?: string;
  routing: Routing;
  address?: string;
}

export interface Revision {
  id: string;
  app_id: string;
  revision: number;
  origin: string;
  body?: AppSpec;
  created_by: string;
  created_at: string;
  ever_pinned: boolean;
}

export interface Deployment {
  id: string;
  app_id: string;
  spec_id: string;
  trigger: string;
  status: string;
  error_code?: string;
  error_detail?: string;
  started_at: string;
  finished_at?: string;
  created_by: string;
}

export interface Detection {
  app_id: string;
  status: string;
  body: unknown;
  answers: (Record<string, string> | null);
  commit?: string;
  started_at: string;
  updated_at: string;
}

export interface GrantRow {
  id: string;
  app_id: string;
  plane: string;
  principal_kind: string;
  principal_id?: string;
  role_id?: string;
  principal_name?: string;
  role_name?: string;
}

export interface User {
  id: string;
  adapter_id: string;
  external_id: string;
  email?: string;
  display_name?: string;
  status: string;
  must_change_password: boolean;
}

export interface Proposal {
  status: string;
  winning_bid: Candidate;
  runners_up: (Candidate[] | null);
  questions: (Question[] | null);
  draft_spec: AppSpec;
  blocked?: Error;
  trial_log?: string;
  commit?: string;
}

export interface Candidate {
  detector: string;
  strategy: string;
  confidence: number;
  evidence?: (string[] | null);
  questions?: (Question[] | null);
  draft?: Draft;
  spec?: AppSpec;
}

export interface Question {
  key: string;
  prompt: string;
  why: string;
  kind: string;
  options?: (string[] | null);
  deferred?: boolean;
}

export interface AppSpec {
  schema_version: number;
  app_id: string;
  revision: number;
  created_at: string;
  created_by: string;
  origin: string;
  source: Source;
  build: Build;
  workloads: (Workload[] | null);
  volumes: (Volume[] | null);
  slots: (Slot[] | null);
  routing: Routing;
  runtime: RuntimeRef;
  deploy: Deploy;
  health: Health;
  resources: Resources;
  egress: Egress;
  retention: Retention;
  warnings?: (Warning[] | null);
}

export interface Error {
  code: string;
  message: string;
  remedy?: string;
  details?: (Record<string, unknown> | null);
  request_id?: string;
}

export interface Document {
  api: API;
  cli: (Command[] | null);
  mcp: (ToolDoc[] | null);
  errors: (CodeDoc[] | null);
  connect: Connect;
  install: Install;
}

export interface Token {
  id: string;
  kind: string;
  name: string;
  owner_user_id?: string;
  expires_at?: string;
  last_used_at?: string;
  revoked_at?: string;
}

export interface Report {
  standing: Standing;
  scan?: Scan;
  counts: Counts;
  worst?: (Finding[] | null);
  scanner?: string;
}

export interface Document {
  source_allowlist?: (string[] | null);
  disabled_verbs?: (string[] | null);
  agent_disabled_verbs?: (string[] | null);
  allow_anonymous_grants?: boolean;
  min_build_isolation?: number;
  min_runtime_isolation?: number;
  egress_allowlist?: (string[] | null);
  require_backup_before_destroy?: boolean;
  max_token_lifetime_days?: number;
  max_log_disk_bytes?: number;
  min_security_score?: number;
  insecure_action?: string;
  insecure_grace_hours?: number;
}

export interface Source {
  type: string;
  url?: string;
  ref?: string;
  commit?: string;
  subdir?: string;
  image?: string;
  digest?: string;
  upload_id?: string;
  credential_ref?: string;
}

export interface Routing {
  adapter_ref: string;
  mode: string;
  mode_source: string;
  hostname?: string;
  path_prefix?: string;
  port?: number;
}

export interface Draft {
  workloads?: (Workload[] | null);
  volumes?: (Volume[] | null);
  slots?: (Slot[] | null);
  build: Build;
  health?: Health;
  warnings?: (Warning[] | null);
}

export interface Build {
  strategy: string;
  adapter_ref: string;
  dockerfile?: string;
  context?: string;
  target?: string;
  compose_file?: string;
  static_dir?: string;
  generated_files?: (Record<string, string> | null);
  args?: (KV[] | null);
  isolation_floor: number;
  timeout_seconds: number;
  egress_mode: string;
  egress_allow?: (string[] | null);
}

export interface Workload {
  name: string;
  image?: string;
  command?: (string[] | null);
  entrypoint?: (string[] | null);
  working_dir?: string;
  env?: (EnvEntry[] | null);
  ports?: (Port[] | null);
  mounts?: (Mount[] | null);
  depends_on?: (string[] | null);
  healthcheck?: Healthcheck;
  exposed: boolean;
  primary: boolean;
  resources?: ResourceLimits;
  build?: WorkloadBuild;
}

export interface Volume {
  id: string;
  name: string;
  declared: string;
  size_hint_bytes?: number;
}

export interface Slot {
  key: string;
  type: string;
  required: boolean;
  evidence?: (string[] | null);
  resolution?: Resolution;
}

export interface RuntimeRef {
  adapter_ref: string;
  isolation_floor: number;
}

export interface Deploy {
  strategy: string;
  auto_deploy: AutoDeploy;
  auto_rollback: boolean;
}

export interface Health {
  source: string;
  path?: string;
  port?: number;
  interval_seconds: number;
  timeout_seconds: number;
  retries: number;
}

export interface Resources {
  cpu_millis: number;
  memory_bytes: number;
  disk_bytes: number;
  overridden: boolean;
}

export interface Egress {
  mode: string;
  allowlist?: (string[] | null);
}

export interface Retention {
  log_bytes: number;
  backup_daily_count: number;
  spec_revisions: number;
}

export interface Warning {
  code: string;
  message: string;
  dismissed: boolean;
  dismissed_by?: string;
}

export interface API {
  base_path: string;
  auth: (Auth[] | null);
  routes: (Route[] | null);
}

export interface Command {
  name: string;
  use: string;
  summary: string;
  details?: string;
  flags?: (Flag[] | null);
  children?: (Command[] | null);
}

export interface ToolDoc {
  name: string;
  description: string;
  schema: (Record<string, unknown> | null);
}

export interface CodeDoc {
  code: string;
  status: number;
  meaning: string;
}

export interface Connect {
  server_env: string;
  token_env: string;
  login_cmd: string;
  mcp_cmd: string;
}

export interface Install {
  repo: string;
  module: string;
  homebrew: string;
  packages: (string[] | null);
  archive: string;
  package: string;
  download: string;
  platforms: (string[] | null);
  in_container: string;
}

export interface Standing {
  verdict: string;
  score?: number;
  threshold: number;
  scanned: string;
  stop_at: string;
}

export interface Scan {
  id: string;
  app_id: string;
  spec_id?: string;
  scanner_ref: string;
  scanner?: string;
  score?: number;
  findings: (Finding[] | null);
  error?: string;
  ran_at: string;
}

export interface Counts {
  critical: number;
  high: number;
  medium: number;
  low: number;
  unknown: number;
}

export interface Finding {
  id: string;
  severity: string;
  title: string;
  target: string;
  fix?: string;
}

export interface KV {
  key: string;
  value: string;
}

export interface EnvEntry {
  key: string;
  value?: string;
  slot_ref?: string;
  secret_ref?: string;
  source?: string;
}

export interface Port {
  number: number;
  protocol: string;
  source: string;
}

export interface Mount {
  volume_id: string;
  path: string;
  read_only: boolean;
}

export interface Healthcheck {
  command?: (string[] | null);
  path?: string;
  port?: number;
  interval_seconds?: number;
  timeout_seconds?: number;
  retries?: number;
}

export interface ResourceLimits {
  cpu_millis?: number;
  memory_bytes?: number;
}

export interface WorkloadBuild {
  context?: string;
  dockerfile?: string;
  target?: string;
}

export interface Resolution {
  mode: string;
  service_ref?: string;
  target?: string;
  secret_ref?: string;
}

export interface AutoDeploy {
  enabled: boolean;
  trigger?: string;
  branch?: string;
}

export interface Auth {
  name: string;
  how: string;
  description: string;
}

export interface Route {
  method: string;
  path: string;
  group: string;
  summary: string;
  verb?: string;
}

export interface Flag {
  name: string;
  shorthand?: string;
  description: string;
  default?: string;
}

