#!/usr/bin/env python3
"""Generate docs/traceability/requirements-index.md from the source documents.

Every R-### is extracted from docs/requirements.md, then cross-referenced against
the design documents (where it is specified), the phase plan (when it gets built),
and the Go test corpus (whether it is covered, per the TestR###_ convention from
design 00 section 4).

Regenerate with `make requirements-index`. Do not hand-edit the output.
"""

from __future__ import annotations

import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REQUIREMENTS = ROOT / "docs" / "requirements.md"
DESIGN_DIR = ROOT / "docs" / "design"
PLAN_DIR = ROOT / "docs" / "plan"
OUT = ROOT / "docs" / "traceability" / "requirements-index.md"

RID = re.compile(r"R-\d{3}")
DEFINITION = re.compile(r"^\*\*(R-\d{3})\s*((?:\[[^\]]+\]\s*)*)\*\*\s*(.*)$")
HEADING = re.compile(r"^##+\s+(.*)$")
TEST_NAME = re.compile(r"func\s+(TestR(\d{3})\w*)\s*\(")


def summarize(text: str, limit: int = 96) -> str:
    """First sentence of a requirement, flattened for a table cell."""
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"\*(.+?)\*", r"\1", text)
    text = text.replace("|", "\\|").strip()
    for end in (". ", ".\n"):
        if end in text:
            text = text.split(end)[0] + "."
            break
    if len(text) > limit:
        text = text[: limit - 1].rsplit(" ", 1)[0] + "…"
    return text or "—"


def parse_requirements() -> list[dict]:
    reqs: list[dict] = []
    section = ""
    for line in REQUIREMENTS.read_text().splitlines():
        heading = HEADING.match(line)
        if heading:
            section = heading.group(1).strip()
            continue
        found = DEFINITION.match(line.strip())
        if found:
            rid, tag, body = found.groups()
            reqs.append(
                {
                    "id": rid,
                    "tag": " ".join(re.findall(r"\[([^\]]+)\]", tag or "")) or "—",
                    "section": section,
                    "summary": summarize(body),
                }
            )
    return reqs


def references(directory: Path, pattern: str) -> dict[str, set[str]]:
    """Map each R-### to the set of files under `directory` that mention it."""
    out: dict[str, set[str]] = defaultdict(set)
    for path in sorted(directory.glob(pattern)):
        text = path.read_text()
        for rid in set(RID.findall(text)):
            out[rid].add(path.stem)
    return out


def test_coverage() -> dict[str, set[str]]:
    """Map each R-### to Go test functions named for it (design 00 section 4)."""
    out: dict[str, set[str]] = defaultdict(set)
    for path in ROOT.rglob("*_test.go"):
        if "/node_modules/" in str(path):
            continue
        for name, digits in TEST_NAME.findall(path.read_text()):
            out[f"R-{digits}"].add(name)
    return out


def phase_label(stems: set[str]) -> str:
    numbers = sorted(
        stem.split("-")[1] for stem in stems if stem.startswith("phase-")
    )
    return ", ".join(numbers) if numbers else "—"


def report_coverage() -> int:
    """Print acceptance-test coverage without rewriting the index. For CI."""
    reqs = parse_requirements()
    tests = test_coverage()
    missing = [r["id"] for r in reqs if not tests.get(r["id"])]
    print(f"{len(reqs) - len(missing)}/{len(reqs)} requirements have a named acceptance test")
    if missing:
        print()
        print("No test:", ", ".join(missing))
    return 0


def main() -> None:
    if "--coverage" in sys.argv:
        raise SystemExit(report_coverage())

    reqs = parse_requirements()
    design = references(DESIGN_DIR, "*.md")
    plan = references(PLAN_DIR, "*.md")
    tests = test_coverage()

    designed = [r for r in reqs if design.get(r["id"])]
    planned = [r for r in reqs if phase_label(plan.get(r["id"], set())) != "—"]
    covered = [r for r in reqs if tests.get(r["id"])]

    lines = [
        "# Requirement traceability",
        "",
        "**Generated by `scripts/gen-requirements-index.py`. Do not hand-edit** — run",
        "`make requirements-index` instead.",
        "",
        "Every requirement in `../requirements.md`, cross-referenced against the design documents that",
        "specify it, the phase that builds it, and the tests that prove it. Test coverage follows the",
        "`TestR###_…` convention from design 00 §4.",
        "",
        "| | Count | Of total |",
        "|---|---:|---:|",
        f"| Requirements | {len(reqs)} | — |",
        f"| Specified in a design doc | {len(designed)} | {len(designed) * 100 // len(reqs)}% |",
        f"| Assigned to a phase | {len(planned)} | {len(planned) * 100 // len(reqs)}% |",
        f"| Covered by a named test | {len(covered)} | {len(covered) * 100 // len(reqs)}% |",
        "",
        "A requirement with no design reference is not necessarily a gap — it may be philosophy (R-002),",
        "a non-goal (R-010–R-016), or deferred (R-290+). A requirement with no *test* is either",
        "philosophy, deferred, or a real gap, and the difference should be stated rather than assumed.",
        "",
        "## Index",
        "",
        "| ID | Tag | Requirement | Section | Design | Phase | Tests |",
        "|---|---|---|---|---|---|---|",
    ]

    for r in reqs:
        rid = r["id"]
        design_refs = ", ".join(sorted(d.split("-")[0] for d in design.get(rid, set()) if d[0].isdigit())) or "—"
        test_refs = ", ".join(f"`{t}`" for t in sorted(tests.get(rid, set()))) or "—"
        lines.append(
            f"| **{rid}** | {r['tag']} | {r['summary']} | {r['section']} "
            f"| {design_refs} | {phase_label(plan.get(rid, set()))} | {test_refs} |"
        )

    lines += [
        "",
        "## Requirements with no design reference",
        "",
        "Check each against the categories above before treating it as a gap.",
        "",
    ]
    orphans = [r for r in reqs if not design.get(r["id"])]
    for r in orphans:
        lines.append(f"- **{r['id']}** ({r['section']}) — {r['summary']}")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(
        f"{OUT.relative_to(ROOT)}: {len(reqs)} requirements, "
        f"{len(designed)} designed, {len(planned)} planned, {len(covered)} tested"
    )


if __name__ == "__main__":
    main()
